console.log("hello");

// Project Euler #2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


const fibNumEvn = (maxNum, num1, num2) => {
  let prevNum = num1; // 2
  let prevSum = num2; // 4
  let sum = 0;

  while (sum < maxNum) {
    sum = prevSum + prevNum
    prevNum = prevSum;
    prevSum = sum;
    if (sum < maxNum) {
      console.log("prevNum", prevNum);
      console.log("sum", sum);
    }

    // current num + next num = sum
    // sum + prev num = sum (only if sum < 100)
  }

}

fibNumEvn(4000000000, 2, 4);
